branches:
  only:
    - master

environment:
  matrix:
    - image: Visual Studio 2013
      CMAKE_GENERATOR: 12
    - image: Visual Studio 2015
      CMAKE_GENERATOR: 14

platform: x64
configuration: Release

build_script:
  - cmake -G "Visual Studio %CMAKE_GENERATOR% Win64" -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - Release\mustache.exe
